import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {redirect, usePathname} from "next/navigation";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={'flex m-4'.concat(' ', inter.className)}>
          <aside className='w-[274px] mr-[100px]'>
              <ul>
                <li>
                  <div>
                    Step1
                  </div>
                </li>
                <li>
                  <div>
                    Step2
                  </div>
                </li>
                <li>
                  <div>
                    Step3
                  </div>
                </li>
                <li>
                  <div>
                    Step4
                  </div>
                </li>
              </ul>
          </aside>
          {children}
      </body>
    </html>
  );
}
